#!/usr/bin/env bats

# Task 4 subtask B: the V3 short lifecycle CLI. Each test starts from a separate
# EMPTY neutral temp directory so no real project layout is ever touched. The
# CLI is the only binary under test: it must delegate to the Engine and Arbiter
# and never write current_stage transitions or construct menu text/binding
# itself. create-short is the single entry into the canonical short lifecycle;
# show/apply-result/resolve advance and observe it.

setup() {
    REPO="$BATS_TEST_DIRNAME/.."
    CLI="$REPO/scripts/workflow-v3.js"
    STARTUP="$REPO/scripts/short-startup-entry.js"
    TMP_DIR="$(mktemp -d)"
    PROJECT="$TMP_DIR/book"
    mkdir -p "$PROJECT"
    # An invocation cwd SEPARATE from both the repo/worktree cwd and $PROJECT.
    # Empty/whitespace --project-root regressions used to path.resolve('') to the
    # process cwd and write 追踪/ there; these tests must launch from this empty
    # directory and assert it stays empty (no 追踪/) so the regression can never
    # silently pass by writing into the repo/worktree cwd where it goes unseen.
    INVOCATION_CWD="$TMP_DIR/invocation-cwd"
    mkdir -p "$INVOCATION_CWD"
}

# Helper: a sorted, newline-joined listing of the invocation cwd's top level,
# excluding '.'/'..'. Used as a before/after snapshot so any stray write (not
# just 追踪/) is detected. The directory starts empty, so a stable invocation
# leaves it empty.
invocation_listing() {
    find "$INVOCATION_CWD" -mindepth 1 -maxdepth 1 | sort
}

teardown() {
    rm -rf "$TMP_DIR"
}

# Helper: invoke create-short via `run`, then persist the emitted JSON payload
# to a file for the node assertion block and return the workflow id in $WFID.
create_short() {
    local profile="$1"
    local goal="$2"
    run node "$CLI" create-short \
        --project-root "$PROJECT" \
        --profile "$profile" \
        --user-goal "$goal" \
        --json
    printf '%s\n' "$output" > "$TMP_DIR/create.json"
}

# Helper: invoke the default short-startup-entry (the host-facing startup router)
# via `run` with the given extra args, then persist its JSON payload.
startup_entry() {
    run node "$STARTUP" --project-root "$PROJECT" --json "$@"
    printf '%s\n' "$output" > "$TMP_DIR/startup.json"
}

# Helper: invoke apply-result via `run` and persist its JSON payload.
apply_result() {
    local expected="$1"
    run node "$CLI" apply-result \
        --project-root "$PROJECT" \
        --workflow-id "$WFID" \
        --expected-version "$expected" \
        --result-file "$TMP_DIR/result.json" \
        --json
    printf '%s\n' "$output" > "$TMP_DIR/apply.json"
}

# Helpers: substring asserts that use `test` (not `[[ ]]`). The D2 review-fix
# tests assert negative matches mid-test, and a mid-test `[[ ]]` failure does
# NOT abort a bats test under this shell, so every substring check is routed
# through grep + `[ ]` to guarantee a real nonzero exit on failure.
assert_contains() {  # <needle>
    local needle="$1"
    printf '%s' "$output" | grep -F -- "$needle" >/dev/null
}
refute_contains() {  # <needle>
    local needle="$1"
    if printf '%s' "$output" | grep -F -- "$needle" >/dev/null; then
        echo "expected output NOT to contain: $needle" >&3
        echo "actual: $output" >&3
        return 1
    fi
}

# create-short must persist the canonical FIRST durable task for the short
# lifecycle. Every contract field is asserted against the durable task.json,
# not just the in-memory return value, because task.json is the authority.

@test "public create-short persists a V3 short_write task at creative_entry with short-v3 kernel and portable book_root" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/create.json" "$PROJECT" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [outFile, root] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
const task = payload.task;

// The returned task carries the full V3 contract identity.
assert.equal(task.workflow_type, 'short_write');
assert.equal(task.workflow_profile, 'public');
assert.equal(task.production_kernel, 'short-v3');
assert.equal(task.current_stage, 'creative_entry');
assert.equal(task.book_root, '.', 'book_root must stay portable');
assert.ok(/^wf-/.test(task.workflow_id), 'workflow_id must be generated by createWorkflowId');
assert.equal(Number(task.state_version), 1);

// All three contract versions are stamped on the durable task.json.
const file = path.join(root, '追踪', 'workflow', 'tasks', task.workflow_id, 'task.json');
assert.ok(fs.existsSync(file), 'durable task.json must exist');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(Number(persisted.engine_version), 3);
assert.equal(Number(persisted.task_schema_version), 3);
assert.equal(Number(persisted.workflow_contract_version), 3);
assert.equal(persisted.workflow_type, 'short_write');
assert.equal(persisted.workflow_profile, 'public');
assert.equal(persisted.production_kernel, 'short-v3');
assert.equal(persisted.current_stage, 'creative_entry');
assert.equal(persisted.book_root, '.');
NODE
}

@test "private create-short persists a V3 short_write task at creative_entry with short-v3 kernel and portable book_root" {
    create_short private "私密短篇"
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/create.json" "$PROJECT" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [outFile, root] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
const task = payload.task;

assert.equal(task.workflow_type, 'short_write');
assert.equal(task.workflow_profile, 'private');
assert.equal(task.production_kernel, 'short-v3');
assert.equal(task.current_stage, 'creative_entry');
assert.equal(task.book_root, '.');
assert.ok(/^wf-/.test(task.workflow_id));
assert.equal(Number(task.state_version), 1);

const file = path.join(root, '追踪', 'workflow', 'tasks', task.workflow_id, 'task.json');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(Number(persisted.engine_version), 3);
assert.equal(Number(persisted.task_schema_version), 3);
assert.equal(Number(persisted.workflow_contract_version), 3);
    assert.equal(persisted.workflow_profile, 'private');
    assert.equal(persisted.production_kernel, 'short-v3');
    assert.equal(persisted.current_stage, 'creative_entry');
NODE
}

@test "repeating create-short for the same unfinished goal resumes the family head without creating a competing branch" {
    create_short private "新开短篇"
    [ "$status" -eq 0 ]
    cp "$TMP_DIR/create.json" "$TMP_DIR/first-create.json"

    create_short private "新开短篇"
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/first-create.json" "$TMP_DIR/create.json" "$PROJECT" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [firstFile, secondFile, root] = process.argv.slice(2);
const first = JSON.parse(fs.readFileSync(firstFile, 'utf8'));
const second = JSON.parse(fs.readFileSync(secondFile, 'utf8'));

assert.equal(second.resumed_existing, true, 'the second create must report a durable resume');
assert.equal(second.task.workflow_id, first.task.workflow_id, 'the family head must remain the only workflow');

const tasksDir = path.join(root, '追踪', 'workflow', 'tasks');
const taskIds = fs.readdirSync(tasksDir).filter((id) => fs.existsSync(path.join(tasksDir, id, 'task.json')));
assert.deepEqual(taskIds, [first.task.workflow_id], 'no competing task directory may be created');

const familyFile = path.join(root, '追踪', 'workflow', 'families', first.task.task_family_id, 'family.json');
const family = JSON.parse(fs.readFileSync(familyFile, 'utf8'));
assert.equal(family.head_workflow_id, first.task.workflow_id);
assert.equal(family.branches.length, 1, 'idempotent startup must not append a sibling branch');
NODE
}

# A plain create-short must persist the durable task-family provenance that the
# real chapter-commit transaction path requires (task_family_id, branch_id,
# branch_status), plus the family record on disk — exactly like the V2 state
# machine does at create. Without it, a plain V3 task cannot commit a real
# setting or outline. This proves the create flow registers the family itself;
# no separate startup wrapper or ensureTaskFamily call is needed.

@test "public create-short persists task-family provenance so a plain V3 task can commit without a separate startup step" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/create.json" "$PROJECT" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [outFile, root] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
const task = payload.task;

// The durable task carries durable commit provenance stamped at creation.
assert.ok(String(task.task_family_id || '').trim(), 'create-short must stamp task_family_id');
assert.equal(task.branch_id, task.workflow_id, 'create-short must stamp branch_id = workflow_id');
assert.ok(String(task.branch_status || '').trim(), 'create-short must stamp branch_status');

const file = path.join(root, '追踪', 'workflow', 'tasks', task.workflow_id, 'task.json');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(persisted.task_family_id, task.task_family_id);
assert.equal(persisted.branch_id, task.workflow_id);
assert.equal(persisted.branch_status, task.branch_status);

// The family record exists on disk and this workflow is the head branch.
const family = JSON.parse(fs.readFileSync(
  path.join(root, '追踪', 'workflow', 'families', task.task_family_id, 'family.json'), 'utf8'));
assert.equal(family.head_workflow_id, task.workflow_id);
NODE
}

# Both profiles must enter the first professional stage through the explicit
# author-owned creative_entry result. Later production stages must use
# run-stage/run-current-stage and cannot be advanced by a handwritten packet.

@test "public profile advances the author entry to material_positioning" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    printf '{"kind":"completed","code":"advance","stage_id":"creative_entry"}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/apply.json" "$PROJECT" "$WFID" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [applyFile, root, workflowId] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(applyFile, 'utf8'));
assert.equal(payload.task.current_stage, 'material_positioning');
assert.equal(payload.visible_response, null, 'completed results carry no interaction');
assert.equal(Number(payload.task.state_version), 2);

// The durable task.json agrees with the rendered snapshot.
const file = path.join(root, '追踪', 'workflow', 'tasks', workflowId, 'task.json');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(persisted.current_stage, 'material_positioning');
assert.equal(Number(persisted.state_version), 2);
NODE
}

@test "private profile advances the author entry to material_positioning" {
    create_short private "私密短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    printf '{"kind":"completed","code":"advance","stage_id":"creative_entry"}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/apply.json" "$PROJECT" "$WFID" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [applyFile, root, workflowId] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(applyFile, 'utf8'));
assert.equal(payload.task.current_stage, 'material_positioning');
assert.equal(Number(payload.task.state_version), 2);
const file = path.join(root, '追踪', 'workflow', 'tasks', workflowId, 'task.json');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(persisted.current_stage, 'material_positioning');
assert.equal(persisted.workflow_profile, 'private');
NODE
}

@test "public apply-result cannot fabricate completion for a professional production stage" {
    create_short private "新开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    printf '{"kind":"completed","code":"author_entry_confirmed","stage_id":"creative_entry"}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    local task_file="$PROJECT/追踪/workflow/tasks/$WFID/task.json"
    local before
    before=$(shasum -a 256 "$task_file" | awk '{print $1}')
    printf '{"kind":"completed","code":"fabricated_empty_stage","stage_id":"material_positioning"}\n' > "$TMP_DIR/result.json"
    apply_result 2
    [ "$status" -ne 0 ]
    assert_contains "professional_stage_requires_run_stage"

    local after
    after=$(shasum -a 256 "$task_file" | awk '{print $1}')
    [ "$before" = "$after" ]
}

# show must render an interaction ONLY when a committed pending action exists.
# It delegates the menu text and four-field binding to renderCommittedInteraction
# and never constructs either itself.

@test "show renders no interaction when no committed pending action exists" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    run node "$CLI" show --project-root "$PROJECT" --workflow-id "$WFID" --json
    [ "$status" -eq 0 ]
    printf '%s\n' "$output" > "$TMP_DIR/show.json"

    node - "$TMP_DIR/show.json" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
// The task snapshot is returned, but no interaction is rendered.
assert.equal(payload.task.current_stage, 'creative_entry');
assert.equal(payload.interaction, null, 'no pending action means no rendered interaction');
NODE
}

@test "show renders the committed interaction via renderCommittedInteraction when a pending action exists" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    # A needs_author_choice result keeps the node and commits a pending action.
    printf '{"kind":"needs_author_choice","code":"pick","stage_id":"creative_entry","question":"选哪个","options":[{"action_id":"a","label":"甲"},{"action_id":"b","label":"乙"}]}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    run node "$CLI" show --project-root "$PROJECT" --workflow-id "$WFID" --json
    [ "$status" -eq 0 ]
    printf '%s\n' "$output" > "$TMP_DIR/show.json"

    node - "$TMP_DIR/show.json" "$TMP_DIR/apply.json" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const [showFile, applyFile] = process.argv.slice(2);
const show = JSON.parse(fs.readFileSync(showFile, 'utf8'));
const apply = JSON.parse(fs.readFileSync(applyFile, 'utf8'));

// The interaction is rendered by the Arbiter off the committed pending action.
assert.ok(show.interaction, 'a committed pending action must be rendered');
assert.ok(show.interaction.text.includes('选哪个'), 'rendered text carries the question');
assert.ok(show.interaction.text.includes('1. 甲'), 'rendered text carries the Arbiter-assigned option number');

// The binding is exactly the four Arbiter-owned fields, matching apply-result.
const keys = Object.keys(show.interaction.binding).sort();
assert.deepEqual(keys, ['pending_action_id', 'state_version', 'visible_choice_hash', 'workflow_id']);
assert.deepEqual(show.interaction.binding, apply.task.pending_action && {
    workflow_id: apply.task.pending_action.workflow_id,
    state_version: apply.task.pending_action.state_version,
    pending_action_id: apply.task.pending_action.id,
    visible_choice_hash: apply.task.pending_action.visible_choice_hash,
});
NODE
}

# resolve consumes an input-file that carries the four-field binding plus the
# author's choice number, and atomically marks the pending action resolved.

@test "resolve consumes an input-file binding and durably marks the pending action resolved" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    printf '{"kind":"needs_author_choice","code":"pick","stage_id":"creative_entry","question":"选哪个","options":[{"action_id":"a","label":"甲"},{"action_id":"b","label":"乙"}]}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    # Build the input-file from the committed binding, adding the author choice.
    node - "$TMP_DIR/apply.json" "$TMP_DIR/input.json" <<'NODE'
const fs = require('fs');
const [applyFile, inputFile] = process.argv.slice(2);
const apply = JSON.parse(fs.readFileSync(applyFile, 'utf8'));
const b = apply.visible_response.binding;
fs.writeFileSync(inputFile, `${JSON.stringify({
    workflow_id: b.workflow_id,
    state_version: b.state_version,
    pending_action_id: b.pending_action_id,
    visible_choice_hash: b.visible_choice_hash,
    choice: '1',
})}\n`);
NODE

    run node "$CLI" resolve --project-root "$PROJECT" --workflow-id "$WFID" --expected-version 2 --input-file "$TMP_DIR/input.json" --json
    [ "$status" -eq 0 ]
    printf '%s\n' "$output" > "$TMP_DIR/resolve.json"

    node - "$TMP_DIR/resolve.json" "$PROJECT" "$WFID" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [resolveFile, root, workflowId] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(resolveFile, 'utf8'));

// The consumed selection maps choice '1' to the first option.
assert.equal(payload.selection.action_id, 'a');
assert.equal(payload.selection.label, '甲');
assert.equal(Number(payload.selection.number), 1);

// The durable task.json advanced and recorded the resolved selection.
const file = path.join(root, '追踪', 'workflow', 'tasks', workflowId, 'task.json');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(Number(persisted.state_version), 3);
assert.equal(persisted.pending_action.status, 'resolved');
assert.deepEqual(persisted.pending_action.selection, { action_id: 'a', label: '甲', number: 1 });
NODE
}

# A stale expected-version must exit nonzero AND leave the durable task.json
# byte-for-byte unchanged — the engine rejects before any write.

@test "apply-result with a stale expected-version exits nonzero without writing" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    printf '{"kind":"needs_author_choice","code":"pick","stage_id":"creative_entry","question":"选哪个","options":[{"action_id":"a","label":"甲"},{"action_id":"b","label":"乙"}]}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    TASK_FILE="$PROJECT/追踪/workflow/tasks/$WFID/task.json"
    BEFORE=$(cat "$TASK_FILE")

    # Replaying the now-stale expected-version 1 must fail and not write.
    run node "$CLI" apply-result --project-root "$PROJECT" --workflow-id "$WFID" --expected-version 1 --result-file "$TMP_DIR/result.json" --json
    [ "$status" -ne 0 ]
    printf '%s\n' "$output" > "$TMP_DIR/stale.json"

    AFTER=$(cat "$TASK_FILE")
    [ "$BEFORE" = "$AFTER" ]

    node - "$TMP_DIR/stale.json" <<'NODE'
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
if (payload.ok !== false) process.exit(1);
NODE
}

@test "resolve with a stale expected-version exits nonzero without writing" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    printf '{"kind":"needs_author_choice","code":"pick","stage_id":"creative_entry","question":"选哪个","options":[{"action_id":"a","label":"甲"},{"action_id":"b","label":"乙"}]}\n' > "$TMP_DIR/result.json"
    apply_result 1
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/apply.json" "$TMP_DIR/input.json" <<'NODE'
const fs = require('fs');
const [applyFile, inputFile] = process.argv.slice(2);
const apply = JSON.parse(fs.readFileSync(applyFile, 'utf8'));
const b = apply.visible_response.binding;
fs.writeFileSync(inputFile, `${JSON.stringify({
    workflow_id: b.workflow_id,
    state_version: b.state_version,
    pending_action_id: b.pending_action_id,
    visible_choice_hash: b.visible_choice_hash,
    choice: '1',
})}\n`);
NODE

    TASK_FILE="$PROJECT/追踪/workflow/tasks/$WFID/task.json"
    BEFORE=$(cat "$TASK_FILE")

    # expected-version 1 is stale (the pending action lives at version 2).
    run node "$CLI" resolve --project-root "$PROJECT" --workflow-id "$WFID" --expected-version 1 --input-file "$TMP_DIR/input.json" --json
    [ "$status" -ne 0 ]
    printf '%s\n' "$output" > "$TMP_DIR/stale.json"

    AFTER=$(cat "$TASK_FILE")
    [ "$BEFORE" = "$AFTER" ]
}

# ---------------------------------------------------------------------------
# Subtask C: default startup routing. The host-facing short-startup-entry is
# now the router into the canonical V3 lifecycle. It must default to V3, parse
# the compatibility/profile flags, fail closed on --restart without --legacy-v2
# (the future compatibility gateway), and keep the V2 startup_scan/finalize flow
# ONLY behind explicit --legacy-v2. It is asserted from an EMPTY directory.
# ---------------------------------------------------------------------------

# Default routing invokes the V3 create-short path and wraps the durable task in
# the stable host-facing short_startup_ready output, with no startup_scan stage.

@test "default short-startup-entry on an empty directory routes to V3 create-short and returns short_startup_ready" {
    startup_entry
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/startup.json" "$PROJECT" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [outFile, root] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));

// The host-facing status stays stable across the routing migration.
assert.equal(payload.status, 'short_startup_ready');

// The wrapped task is the V3 first durable task, not a V2 startup_scan task.
const task = payload.task;
assert.equal(task.workflow_type, 'short_write');
assert.equal(Number(task.engine_version), 3, 'engine_version must be 3');
assert.equal(task.production_kernel, 'short-v3');
assert.equal(task.current_stage, 'creative_entry', 'must NOT land on startup_scan');

// The durable task.json agrees with the wrapped task.
const file = path.join(root, '追踪', 'workflow', 'tasks', task.workflow_id, 'task.json');
assert.ok(fs.existsSync(file), 'durable task.json must exist');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(Number(persisted.engine_version), 3);
assert.equal(persisted.production_kernel, 'short-v3');
assert.equal(persisted.current_stage, 'creative_entry');
NODE
}

# --profile public AND --no-private-registry both map to the public profile;
# the default (no flag) maps to private.

@test "short-startup-entry --profile public maps to the public V3 profile" {
    startup_entry --profile public
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/startup.json" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
assert.equal(payload.status, 'short_startup_ready');
assert.equal(payload.task.workflow_profile, 'public');
assert.equal(payload.task.production_kernel, 'short-v3');
NODE
}

@test "short-startup-entry --no-private-registry maps to the public V3 profile" {
    startup_entry --no-private-registry
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/startup.json" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
assert.equal(payload.status, 'short_startup_ready');
assert.equal(payload.task.workflow_profile, 'public');
NODE
}

@test "short-startup-entry default (no profile flag) maps to the private V3 profile" {
    startup_entry
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/startup.json" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
assert.equal(payload.status, 'short_startup_ready');
assert.equal(payload.task.workflow_profile, 'private');
NODE
}

# --restart without --legacy-v2 is the future compatibility gateway: it must
# fail closed (nonzero, structured payload) rather than silently routing V2 or V3.

@test "short-startup-entry --restart without --legacy-v2 fails closed at the compatibility gateway" {
    startup_entry --restart --reason "重新规划热点资讯发现流程"
    [ "$status" -ne 0 ]

    node - "$TMP_DIR/startup.json" <<'NODE'
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
if (payload.status !== 'short_startup_restart_gateway_closed') process.exit(1);
NODE

    # A failed gateway must not leave a focused task behind.
    [ ! -f "$PROJECT/追踪/workflow/current-task.json" ]
}

# --legacy-v2 remains parse-compatible but must not create another writable V2
# task after the V3 production entry is available.

@test "short-startup-entry --legacy-v2 fails closed without creating a V2 task" {
    startup_entry --legacy-v2
    [ "$status" -eq 2 ]
    [[ "$output" == *'blocked_v2_short_write_frozen'* ]]
    [ ! -f "$PROJECT/追踪/workflow/current-task.json" ]
}

# ---------------------------------------------------------------------------
# Task 4 review fix D2: CLI/startup authority and argument safety. The CLI
# must never define or pass current_stage (the Engine stamps it); each command
# rejects unknown flags against a command-specific whitelist with usage exit 2;
# the startup router validates value flags before path.resolve/write so a
# missing value or a following --flag yields a stable usage error (exit 2)
# instead of a stack trace, and never creates a directory named --json.
# Conflicting --profile private with --no-private-registry is rejected.
# ---------------------------------------------------------------------------

# create-short must NOT pass current_stage to the Engine: the Engine is the
# sole authority for that field. Even a value matching the canonical entry must
# be rejected as engine authority, not echoed from the command line.

@test "create-short never passes current_stage to the engine (engine stamps creative_entry)" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]

    # A stale engine guard that rejected caller-supplied current_stage proves the
    # CLI is NOT forwarding it. create-short succeeds, so current_stage never
    # reached the Engine from the command line.
    node - "$TMP_DIR/create.json" "$PROJECT" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [outFile, root] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
const task = payload.task;
// The Engine stamped creative_entry itself; the CLI did not supply it.
assert.equal(task.current_stage, 'creative_entry');
// The durable task.json carries the same engine-stamped stage.
const file = path.join(root, '追踪', 'workflow', 'tasks', task.workflow_id, 'task.json');
const persisted = JSON.parse(fs.readFileSync(file, 'utf8'));
assert.equal(persisted.current_stage, 'creative_entry');
NODE

    # current_stage is Engine authority: the CLI must NOT accept it on the
    # command line at all (it is absent from the whitelist). Passing it is a
    # usage error (exit 2), not a forwarded value — so the engine-owned field
    # can never be set by a caller, even to the canonical entry.
    OTHER="$TMP_DIR/other"
    mkdir -p "$OTHER"
    run node "$CLI" create-short --project-root "$OTHER" --profile public \
        --user-goal "x" --current-stage setting --json
    [ "$status" -eq 2 ]
    assert_contains "create-short"
    refute_contains "create_failed"
    # No task was written for the rejected invocation.
    [ ! -f "$OTHER/追踪/workflow/current-task.json" ]
}

# Each CLI command rejects unknown flags against a command-specific whitelist
# with usage exit 2 (not a stack trace, not exit 1 ok:false).

@test "create-short rejects an unknown flag with usage exit 2" {
    run node "$CLI" create-short --project-root "$PROJECT" --profile public \
        --user-goal "x" --bogus value --json
    [ "$status" -eq 2 ]
    assert_contains "create-short" || assert_contains "bogus"
}

@test "show rejects an unknown flag with usage exit 2" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    run node "$CLI" show --project-root "$PROJECT" --workflow-id "$WFID" --nope --json
    [ "$status" -eq 2 ]
}

@test "apply-result rejects an unknown flag with usage exit 2" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    run node "$CLI" apply-result --project-root "$PROJECT" --workflow-id "$WFID" \
        --expected-version 1 --result-file "$TMP_DIR/result.json" --flag-zzz --json
    [ "$status" -eq 2 ]
}

@test "resolve rejects an unknown flag with usage exit 2" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    run node "$CLI" resolve --project-root "$PROJECT" --workflow-id "$WFID" \
        --expected-version 1 --input-file "$TMP_DIR/input.json" --surprise --json
    [ "$status" -eq 2 ]
}

# A flag valid for one command but not another is still unknown for that command.

@test "show rejects the create-short-only --profile flag as unknown with usage exit 2" {
    create_short public "公开短篇"
    [ "$status" -eq 0 ]
    WFID=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$TMP_DIR/create.json','utf8')).task.workflow_id)")

    run node "$CLI" show --project-root "$PROJECT" --workflow-id "$WFID" --profile public --json
    [ "$status" -eq 2 ]
}

# The startup router's value flags (--project-root, --user-goal, --reason) must
# reject a missing value (end of args) AND a following --flag, returning a
# stable usage error with exit 2 instead of a stack trace. A following --flag
# must never be consumed as the value (which would create a directory named
# --json or similar).

@test "startup --project-root with no value fails with usage exit 2 and no write" {
    run node "$STARTUP" --project-root --json
    [ "$status" -eq 2 ]
    assert_contains "--project-root"
    # No directory named --json was created in the cwd.
    [ ! -d "./--json" ]
    [ ! -d "$BATS_TEST_TMPDIR/--json" ]
}

@test "startup --user-goal followed by --json fails with usage exit 2 and creates no --json dir" {
    run node "$STARTUP" --project-root "$PROJECT" --user-goal --json
    [ "$status" -eq 2 ]
    assert_contains "--user-goal"
    # The router itself short-circuits with a stable usage error: it must NOT
    # leak the bad value into create-short (no create_failed / invalid_script_output).
    refute_contains "create_failed"
    refute_contains "invalid_script_output"
    [ ! -d "$PROJECT/--json" ]
    # No task was created.
    [ ! -f "$PROJECT/追踪/workflow/current-task.json" ]
}

@test "startup --reason with no value fails with usage exit 2" {
    run node "$STARTUP" --project-root "$PROJECT" --reason
    [ "$status" -eq 2 ]
    assert_contains "--reason"
}

@test "startup --reason followed by --legacy-v2 fails with usage exit 2 (no value swallowing)" {
    run node "$STARTUP" --project-root "$PROJECT" --reason --legacy-v2
    [ "$status" -eq 2 ]
    assert_contains "--reason"
}

# The usage error must be a stable string, not a thrown stack trace.

@test "startup value-flag failure returns a stable usage error without a stack trace" {
    run node "$STARTUP" --project-root "$PROJECT" --user-goal --json
    [ "$status" -eq 2 ]
    # The router itself prints a single stable usage line: no JS stack-trace
    # artifacts (at Object / at parseArgs / throw new Error) and no downstream
    # create-short failure leaking through.
    assert_contains "--user-goal"
    refute_contains "    at "
    refute_contains "throw new Error"
    refute_contains "create_failed"
}

# Conflicting profile flags are rejected.

@test "startup --profile private with --no-private-registry is rejected with usage exit 2" {
    run node "$STARTUP" --project-root "$PROJECT" --profile private --no-private-registry --json
    [ "$status" -eq 2 ]
    assert_contains "profile"
    [ ! -f "$PROJECT/追踪/workflow/current-task.json" ]
}

# An unknown startup argument is rejected with usage exit 2.

@test "startup rejects an unknown argument with usage exit 2" {
    run node "$STARTUP" --project-root "$PROJECT" --whatever --json
    [ "$status" -eq 2 ]
    assert_contains "unknown" || assert_contains "--whatever"
}

# ---------------------------------------------------------------------------
# Task 4 review fix D3: empty value-flag values. A value flag may carry an
# explicit empty string (`--project-root ""`, `--profile ""`). An empty value
# is NOT a real value: it must be a usage error (exit 2) BEFORE path.resolve or
# any create-short invocation, so the router never resolves the cwd or starts a
# task on a blank root/profile. A value that is only whitespace is the same —
# String(value).trim() === '' has no usable content.
# ---------------------------------------------------------------------------

@test "startup --project-root with an empty string fails with usage exit 2 and writes nothing to the invocation cwd" {
    # Launch from a dedicated empty cwd (NOT the repo/worktree cwd). The old
    # implementation path.resolve('') to the process cwd and wrote 追踪/ there;
    # running from this isolated directory makes that regression observable.
    BEFORE="$(invocation_listing)"
    cd "$INVOCATION_CWD" || exit 1
    run node "$STARTUP" --project-root "" --json
    cd - >/dev/null || exit 1
    [ "$status" -eq 2 ]
    assert_contains "--project-root"
    # The router short-circuits before delegating: no create-short failure leaks.
    refute_contains "create_failed"
    refute_contains "invalid_script_output"

    # No task was created anywhere — neither $PROJECT nor the invocation cwd.
    [ ! -f "$PROJECT/追踪/workflow/current-task.json" ]
    [ ! -d "$INVOCATION_CWD/追踪" ]
    AFTER="$(invocation_listing)"
    [ "$BEFORE" = "$AFTER" ]
}

@test "startup --project-root with only whitespace fails with usage exit 2 and writes nothing to the invocation cwd" {
    BEFORE="$(invocation_listing)"
    cd "$INVOCATION_CWD" || exit 1
    run node "$STARTUP" --project-root "   " --json
    cd - >/dev/null || exit 1
    [ "$status" -eq 2 ]
    assert_contains "--project-root"
    refute_contains "create_failed"
    refute_contains "invalid_script_output"

    # A whitespace-only root must resolve to NO directory; the cwd must stay empty.
    [ ! -d "$INVOCATION_CWD/追踪" ]
    AFTER="$(invocation_listing)"
    [ "$BEFORE" = "$AFTER" ]
}

@test "startup --profile with an empty string fails with usage exit 2 before any write" {
    run node "$STARTUP" --project-root "$PROJECT" --profile "" --json
    [ "$status" -eq 2 ]
    assert_contains "--profile"
    refute_contains "create_failed"
    refute_contains "invalid_script_output"
    [ ! -f "$PROJECT/追踪/workflow/current-task.json" ]
}

@test "startup --profile with only whitespace fails with usage exit 2 before any write" {
    run node "$STARTUP" --project-root "$PROJECT" --profile "  " --json
    [ "$status" -eq 2 ]
    assert_contains "--profile"
    refute_contains "create_failed"
}

# The V3 short_startup_ready output keeps the top-level workflow_id equal to the
# wrapped task.workflow_id (hosts key off the top-level field).

@test "default startup short_startup_ready keeps top-level workflow_id equal to task.workflow_id" {
    startup_entry
    [ "$status" -eq 0 ]

    node - "$TMP_DIR/startup.json" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const [outFile] = process.argv.slice(2);
const payload = JSON.parse(fs.readFileSync(outFile, 'utf8'));
assert.equal(payload.status, 'short_startup_ready');
assert.equal(payload.workflow_id, payload.task.workflow_id, 'top-level workflow_id must equal task.workflow_id');
assert.ok(/^wf-/.test(payload.workflow_id));
NODE
}

# ---------------------------------------------------------------------------
# Task 5 Step 6 RED: task-family registration is a REQUIRED create precondition
# that fails CLOSED, and a duplicate workflow id is caught by a creation
# preflight that runs BEFORE family persistence. Both invariants are asserted
# through the V3 engine create path (the same path create-short uses).
# ---------------------------------------------------------------------------

@test "V3 createTask fails closed when task-family persistence fails and writes no task.json" {
    BOOK="$TMP_DIR/family-fail-closed-book"
    mkdir -p "$BOOK"
    # Make the families root a FILE so persistFamily's mkdirSync throws ENOTDIR.
    # This is the side effect that family registration must surface, not swallow.
    mkdir -p "$BOOK/追踪/workflow"
    printf '%s' 'not-a-dir' > "$BOOK/追踪/workflow/families"

    run node - "$REPO" "$BOOK" <<'NODE'
const fs = require('fs');
const path = require('path');
const [repo, root] = process.argv.slice(2);
const engine = require(path.join(repo, 'scripts/lib/workflow-v3/engine.js'));
try {
  engine.createTask(root, { workflow_id: 'wf-fail-closed', workflow_type: 'short_write', user_goal: '写短篇' });
  process.exitCode = 1; // BUG: create must NOT succeed when family persistence fails
} catch (error) {
  // Expected: family persistence failure surfaces and create fails closed.
  process.exitCode = 0;
}
// No durable task may exist after a failed create.
const taskFile = path.join(root, '追踪', 'workflow', 'tasks', 'wf-fail-closed', 'task.json');
if (fs.existsSync(taskFile)) { console.error('task.json must not exist after family failure'); process.exitCode = 1; }
NODE
    if [ "$status" -ne 0 ]; then printf '%s\n' "$output" >&2; fi
    [ "$status" -eq 0 ]
}

@test "V3 createTask rejects a duplicate workflow id in preflight before family persistence, leaving family inventory unchanged" {
    BOOK="$TMP_DIR/family-duplicate-preflight-book"
    mkdir -p "$BOOK"

    # First create succeeds and persists a family + durable task for wf-dup. The
    # durable task.json is KEPT (not removed): the duplicate create must be
    # rejected by the shared task-authority preflight purely from the existing
    # task.json, without workflow-task-authority ever reading the task family.
    run node - "$REPO" "$BOOK" <<'NODE'
const path = require('path');
const [repo, root] = process.argv.slice(2);
const engine = require(path.join(repo, 'scripts/lib/workflow-v3/engine.js'));
engine.createTask(root, { workflow_id: 'wf-dup', workflow_type: 'short_write', user_goal: '首次短篇' });
NODE
    [ "$status" -eq 0 ]

    run node - "$REPO" "$BOOK" <<'NODE'
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const [repo, root] = process.argv.slice(2);
const engine = require(path.join(repo, 'scripts/lib/workflow-v3/engine.js'));

// Snapshot the family inventory + every family file's bytes BEFORE the dup.
const inventoryFile = path.join(root, '追踪', 'workflow', 'task-family-index.json');
const familiesDir = path.join(root, '追踪', 'workflow', 'families');
function snapshot() {
  const inv = fs.existsSync(inventoryFile) ? fs.readFileSync(inventoryFile, 'utf8') : '';
  const files = {};
  if (fs.existsSync(familiesDir)) {
    for (const file of fs.readdirSync(familiesDir)) walk(path.join(familiesDir, file), files);
  }
  return { inv, files: JSON.stringify(files, Object.keys(files).sort()) };
}
function walk(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) walk(full, out);
    else out[path.relative(root, full)] = fs.readFileSync(full, 'utf8');
  }
}
const before = snapshot();

// The first task.json is intentionally KEPT. The duplicate create (same workflow
// id) must be rejected by the shared creation preflight that checks the existing
// task.json BEFORE any family persistence runs. workflow-task-authority never
// reads the task family here — the duplicate is caught from task.json alone.
let rejected = false;
try {
  engine.createTask(root, { workflow_id: 'wf-dup', workflow_type: 'short_write', user_goal: '重复短篇' });
} catch (error) {
  rejected = true;
}
assert.ok(rejected, 'a duplicate workflow id must be rejected before family persistence');

// The family inventory + files must be byte-identical (no second branch / orphan
// promoted by the rejected duplicate).
const after = snapshot();
assert.equal(after.inv, before.inv, 'family inventory must be unchanged by the rejected duplicate');
assert.equal(after.files, before.files, 'family files must be unchanged by the rejected duplicate');
NODE
    [ "$status" -eq 0 ] || { printf '%s\n' "$output" >&2; false; }
}
